name: CI

on:
  push:
    branches: [ main, python-package ]
  pull_request:
    branches: [ main, python-package ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pre-commit
      run: pip install pre-commit
    - name: Run pre-commit hooks
      run: pre-commit run --all-files

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        pip install -r requirements/base.txt
        pip install -r requirements/test.txt
    - name: Run tests
      run: pytest -q
    - name: Build wheel
      run: |
        pip install build
        python -m build --wheel --no-isolation